sudo: true

language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"

addons:
    apt:
        packages:
        - r-base
        - ghc
        - git
        - libgsl0-dev

# adapted from Stack documentation at https://docs.haskellstack.org/en/v1.0.2/travis_ci/
before_install:
    # Set up python
    - pip install pymorlocinternals
    # Set up R
    - mkdir -p ~/R/library
    - echo 'R_LIBS=~/R/library' >> ~/.Renviron
    - R -e 'install.packages("devtools", dependencies=TRUE, repos="https://cloud.r-project.org")'
    - R -e 'devtools::install_github("morloc-project/rmorlocinternals")'
    # Set up Perl
    - export PERL_MM_USE_DEFAULT=1
    - export PERL_CANARY_STABILITY_NOPROMPT=1
    - sudo perl -MCPAN -e 'install JSON::XS' 
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal build --fast
  - stack --no-terminal install
  - mkdir -p $HOME/.morloc/lib
  - mkdir -p $HOME/.morloc/tmp
  - "echo home : $HOME/.morloc > ~/.morloc/config"
  - "echo library : $HOME/.morloc/lib >> ~/.morloc/config"
  - "echo tmpdir : $HOME/.morloc/tmp >> ~/.morloc/config"
  - "echo lang_python3 : python3 >> ~/.morloc/config"
  - morloc install rbase
  - morloc install pybase
  - morloc install cppbase
  - morloc install math
  - stack --no-terminal test --fast

cache:
  directories:
    - $HOME/.stack
